#!/bin/bash
CONFIG=/etc/default/syscemit

if [[ -e ${CONFIG} ]] ; then
    for e in $(cat /etc/default/syscemit); do
        export eval ${e}
    done
else
    export FLASK_ENV=development
fi
export FLASK_APP=run.py

flask ${@}
